name: Lint

on:
  push:
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run stylua
        uses: JohnnyMorganz/stylua-action@76fd70c03e6340ceaf673366712db9b20560b402 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

      - name: Install luacheck
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck

      - name: Run luacheck
        run: luacheck .
